spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: 8080

tutorial:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000








